### ISSUE TITLE
[교환 정보 확인 화면] 신청 책, 등록 책 정보 제대로 띄우기

### ISSUE THREAD

**Issue by 2dubu** [2dubu/LetsBookCrossing#1]
- 직접 입력 시 이미지가 넘어가지 않는 오류 있음
- searchItem 관련 문제 해결

**Comment by lru0409** [comment]
수정 파일
- Assets.xcassets
- ExchangeInfo.swift
- CompleteRegisterViewController.swift
- DirectInputViewController.swift
